### ISSUE TITLE
Colonne des bureaux de fermes écrasés par celle des directions de fermes ?

### ISSUE THREAD

**Issue by robindemourat** [medialab/toflit18_data#25]
Hello,

Depuis aujourd'hui dans le csv de `base_courante` tel que sur `master`, les colonnes `customs_office` et `customs_direction` semblent identiques pour toutes les lignes.

Exemple de code pour reproduire (en python):

```python
import csv

# retrieve relevant flows
with open('./bdd_courante.csv', 'r') as f:
  flows = csv.DictReader(f)
  for flow in flows:
    print(flow['customs_region'], flow['customs_office'])
```

Nous donne:

```bash
Bordeaux Bordeaux
Bordeaux Bordeaux
Bordeaux Bordeaux
Bordeaux Bordeaux
Bordeaux Bordeaux
Bordeaux Bordeaux
Bordeaux Bordeaux
Bordeaux Bordeaux
Bordeaux Bordeaux
# ...
La Rochelle La Rochelle
La Rochelle La Rochelle
La Rochelle La Rochelle
La Rochelle La Rochelle
```

Peut-être une fausse manip quelque part dans un script ?

**Comment by gdaudin** [comment]
Sûrement... Toutes mes excuses. Damned. Je règle cela.
Vous utilisez customs_office ? Pour plus de sûreté, vous pouvez pointer à la place vers customs_office_source. J’ai juste fait un peu de travail de grouping / standardisation sur customs_office suite à une sollicitation d’hier. customs_office_source est exactement l’ancien customs_office.

**Comment by robindemourat** [comment]
Ok merci ! nous pouvons utiliser `customs_office_source` pour plus de sûreté et pour contourner le problème pour l'instant.

**Comment by gdaudin** [comment]
Si tu n’as pas commencé, ne change rien. À la réflexion, c’est plus propre de garder customs_office comme il était et de faire un customs_office_grouping

**Comment by gdaudin** [comment]
Réglé. Je crois. Finalement, on garde customs_office et customs_office_source.
